JB20_085_DM 粒線體資料清理

In [30]:
import numpy as np
import pandas as pd

In [31]:
df = pd.read_csv('JB20_085_DM.csv')

In [32]:
df.head(10)

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,JB20_085
0,chrM,195,.,C,T,15498.77,.,AC=2;AF=1.00;AN=2;DP=361;ExcessHet=3.0103;FS=0...,GT:AD:DP:GQ:PL,"1/1:0,358:358:99:15527,1086,0"
1,chrM,199,rs72619362,T,C,10165.77,.,AC=2;AF=1.00;AN=2;BaseQRankSum=3.439;ClippingR...,GT:AD:DP:GQ:PL,"1/1:26,319:345:99:10194,225,0"
2,chrM,302,rs878871521,A,"AC,ACC",1070.73,.,"AC=1,1;AF=0.500,0.500;AN=2;BaseQRankSum=0.790;...",GT:AD:DP:GQ:PL,"1/2:5,31,14:50:99:1108,215,214,659,0,771"
3,chrM,410,.,A,T,4897.77,.,AC=2;AF=1.00;AN=2;DP=158;ExcessHet=3.0103;FS=0...,GT:AD:DP:GQ:PL,"1/1:0,155:155:99:4926,462,0"
4,chrM,491,.,T,C,9527.77,.,AC=2;AF=1.00;AN=2;BaseQRankSum=1.420;ClippingR...,GT:AD:DP:GQ:PL,"1/1:15,270:285:99:9556,315,0"
5,chrM,515,.,GCA,G,14824.73,.,AC=2;AF=1.00;AN=2;DP=371;ExcessHet=3.0103;FS=0...,GT:AD:DP:GQ:PL,"1/1:0,363:363:99:14862,1092,0"
6,chrM,2354,.,C,T,36833.77,.,AC=2;AF=1.00;AN=2;BaseQRankSum=1.985;ClippingR...,GT:AD:DP:GQ:PL,"1/1:2,1050:1052:99:36862,3115,0"
7,chrM,2485,.,C,T,41702.73,.,AC=2;AF=1.00;AN=2;DP=1189;ExcessHet=3.0103;FS=...,GT:AD:DP:GQ:PL,"1/1:0,1175:1175:99:41740,3523,0"
8,chrM,4049,.,G,A,1389.03,.,AC=1;AF=0.500;AN=2;BaseQRankSum=1.906;Clipping...,GT:AD:DP:GQ:PL,"0/1:5,42:47:12:1417,0,12"
9,chrM,4072,.,C,T,1474.77,.,AC=1;AF=0.500;AN=2;BaseQRankSum=0.028;Clipping...,GT:AD:DP:GQ:PL,"0/1:6,48:54:34:1503,0,34"

In [33]:
df.shape

(80117, 10)

In [34]:
df['GT'],df['AD'],df['DP'],df['GQ'],df['PL'] = df['JB20_085'].str.split(':').str

<ipython-input-34-e29467981546>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df['GT'],df['AD'],df['DP'],df['GQ'],df['PL'] = df['JB20_085'].str.split(':').str

In [35]:
df.head(10)

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,JB20_085,GT,AD,DP,GQ,PL
0,chrM,195,.,C,T,15498.77,.,AC=2;AF=1.00;AN=2;DP=361;ExcessHet=3.0103;FS=0...,GT:AD:DP:GQ:PL,"1/1:0,358:358:99:15527,1086,0",1/1,"0,358",358,99,"15527,1086,0"
1,chrM,199,rs72619362,T,C,10165.77,.,AC=2;AF=1.00;AN=2;BaseQRankSum=3.439;ClippingR...,GT:AD:DP:GQ:PL,"1/1:26,319:345:99:10194,225,0",1/1,"26,319",345,99,"10194,225,0"
2,chrM,302,rs878871521,A,"AC,ACC",1070.73,.,"AC=1,1;AF=0.500,0.500;AN=2;BaseQRankSum=0.790;...",GT:AD:DP:GQ:PL,"1/2:5,31,14:50:99:1108,215,214,659,0,771",1/2,"5,31,14",50,99,"1108,215,214,659,0,771"
3,chrM,410,.,A,T,4897.77,.,AC=2;AF=1.00;AN=2;DP=158;ExcessHet=3.0103;FS=0...,GT:AD:DP:GQ:PL,"1/1:0,155:155:99:4926,462,0",1/1,"0,155",155,99,"4926,462,0"
4,chrM,491,.,T,C,9527.77,.,AC=2;AF=1.00;AN=2;BaseQRankSum=1.420;ClippingR...,GT:AD:DP:GQ:PL,"1/1:15,270:285:99:9556,315,0",1/1,"15,270",285,99,"9556,315,0"
5,chrM,515,.,GCA,G,14824.73,.,AC=2;AF=1.00;AN=2;DP=371;ExcessHet=3.0103;FS=0...,GT:AD:DP:GQ:PL,"1/1:0,363:363:99:14862,1092,0",1/1,"0,363",363,99,"14862,1092,0"
6,chrM,2354,.,C,T,36833.77,.,AC=2;AF=1.00;AN=2;BaseQRankSum=1.985;ClippingR...,GT:AD:DP:GQ:PL,"1/1:2,1050:1052:99:36862,3115,0",1/1,"2,1050",1052,99,"36862,3115,0"
7,chrM,2485,.,C,T,41702.73,.,AC=2;AF=1.00;AN=2;DP=1189;ExcessHet=3.0103;FS=...,GT:AD:DP:GQ:PL,"1/1:0,1175:1175:99:41740,3523,0",1/1,"0,1175",1175,99,"41740,3523,0"
8,chrM,4049,.,G,A,1389.03,.,AC=1;AF=0.500;AN=2;BaseQRankSum=1.906;Clipping...,GT:AD:DP:GQ:PL,"0/1:5,42:47:12:1417,0,12",0/1,"5,42",47,12,"1417,0,12"
9,chrM,4072,.,C,T,1474.77,.,AC=1;AF=0.500;AN=2;BaseQRankSum=0.028;Clipping...,GT:AD:DP:GQ:PL,"0/1:6,48:54:34:1503,0,34",0/1,"6,48",54,34,"1503,0,34"